In [1]:
from torchvision.models import resnet152, feature_extraction
import torch
from torchmocks import mock

/home/nathan/.conda/envs/torchmocks/lib/python3.9/site-packages/tqdm/auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
activations_wishlist = [
    value
    for key, value in torch.nn.modules.activation.__dict__.items()
    if isinstance(value, type) and issubclass(value, torch.nn.Module)
]


In [3]:
net = torch.nn.Transformer(nhead=16, num_encoder_layers=12)
src = torch.rand((10, 32, 512))
tgt = torch.rand((20, 32, 512))
mock(net, debug=True)
out = net.encoder(src)


<class 'torch.nn.modules.linear.NonDynamicallyQuantizableLinear'>
<class 'torch.nn.modules.normalization.LayerNorm'>
<class 'torch.nn.modules.dropout.Dropout'>


In [68]:
net.encoder.layers[0].linear1.__class__

torch.nn.modules.linear.Linear

In [73]:
net.encoder.layers[0].linear1(src )

tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        ...,

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0., 

In [58]:
net.encoder:w

TransformerEncoder(
  (layers): ModuleList(
    (0): TransformerEncoderLayer(
      (self_attn): MultiheadAttention(
        (out_proj): NonDynamicallyQuantizableLinear(in_features=512, out_features=512, bias=True)
      )
      (linear1): Linear(in_features=512, out_features=2048, bias=True)
      (dropout): Dropout(p=0.1, inplace=False)
      (linear2): Linear(in_features=2048, out_features=512, bias=True)
      (norm1): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
      (norm2): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
      (dropout1): Dropout(p=0.1, inplace=False)
      (dropout2): Dropout(p=0.1, inplace=False)
    )
    (1): TransformerEncoderLayer(
      (self_attn): MultiheadAttention(
        (out_proj): NonDynamicallyQuantizableLinear(in_features=512, out_features=512, bias=True)
      )
      (linear1): Linear(in_features=512, out_features=2048, bias=True)
      (dropout): Dropout(p=0.1, inplace=False)
      (linear2): Linear(in_features=2048, out_featu

In [12]:
ndql = torch.nn.modules.linear.NonDynamicallyQuantizableLinear(3, 8)

In [15]:
ndql.__dict__

{'training': True,
 '_parameters': OrderedDict([('weight', Parameter containing:
               tensor([[ 0.0549,  0.5747,  0.4613],
                       [-0.4003, -0.5445,  0.0228],
                       [-0.3018, -0.2229,  0.4856],
                       [ 0.3716,  0.5621,  0.1002],
                       [-0.4930,  0.2379,  0.5583],
                       [-0.3755, -0.4162, -0.2658],
                       [-0.4989, -0.4700, -0.0420],
                       [ 0.0193,  0.2194,  0.0210]], requires_grad=True)),
              ('bias',
               Parameter containing:
               tensor([-0.3542,  0.2347, -0.1731,  0.2280,  0.3959, -0.4210,  0.2893, -0.1959],
                      requires_grad=True))]),
 '_buffers': OrderedDict(),
 '_non_persistent_buffers_set': set(),
 '_backward_hooks': OrderedDict(),
 '_is_full_backward_hook': None,
 '_forward_hooks': OrderedDict(),
 '_forward_pre_hooks': OrderedDict(),
 '_state_dict_hooks': OrderedDict(),
 '_load_state_dict_pre_hooks': Ord

In [27]:
out.shape

torch.Size([20, 32, 512])

In [21]:
t = torch.nn.Transformer()

In [23]:
t.forward?

Signature:
t.forward(
    src: torch.Tensor,
    tgt: torch.Tensor,
    src_mask: Optional[torch.Tensor] = None,
    tgt_mask: Optional[torch.Tensor] = None,
    memory_mask: Optional[torch.Tensor] = None,
    src_key_padding_mask: Optional[torch.Tensor] = None,
    tgt_key_padding_mask: Optional[torch.Tensor] = None,
    memory_key_padding_mask: Optional[torch.Tensor] = None,
) -> torch.Tensor
Docstring:
Take in and process masked source/target sequences.

Args:
    src: the sequence to the encoder (required).
    tgt: the sequence to the decoder (required).
    src_mask: the additive mask for the src sequence (optional).
    tgt_mask: the additive mask for the tgt sequence (optional).
    memory_mask: the additive mask for the encoder output (optional).
    src_key_padding_mask: the ByteTensor mask for src keys per batch (optional).
    tgt_key_padding_mask: the ByteTensor mask for tgt keys per batch (optional).
    memory_key_padding_mask: the ByteTensor mask for memory keys per bat

In [22]:
t()

Transformer(
  (encoder): TransformerEncoder(
    (layers): ModuleList(
      (0): TransformerEncoderLayer(
        (self_attn): MultiheadAttention(
          (out_proj): NonDynamicallyQuantizableLinear(in_features=512, out_features=512, bias=True)
        )
        (linear1): Linear(in_features=512, out_features=2048, bias=True)
        (dropout): Dropout(p=0.1, inplace=False)
        (linear2): Linear(in_features=2048, out_features=512, bias=True)
        (norm1): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
        (norm2): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
        (dropout1): Dropout(p=0.1, inplace=False)
        (dropout2): Dropout(p=0.1, inplace=False)
      )
      (1): TransformerEncoderLayer(
        (self_attn): MultiheadAttention(
          (out_proj): NonDynamicallyQuantizableLinear(in_features=512, out_features=512, bias=True)
        )
        (linear1): Linear(in_features=512, out_features=2048, bias=True)
        (dropout): Dropout(p=0.1, in

Transformer(
  (encoder): TransformerEncoder(
    (layers): ModuleList(
      (0): TransformerEncoderLayer(
        (self_attn): MultiheadAttention(
          (out_proj): NonDynamicallyQuantizableLinear(in_features=512, out_features=512, bias=True)
        )
        (linear1): Linear(in_features=512, out_features=2048, bias=True)
        (dropout): Dropout(p=0.1, inplace=False)
        (linear2): Linear(in_features=2048, out_features=512, bias=True)
        (norm1): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
        (norm2): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
        (dropout1): Dropout(p=0.1, inplace=False)
        (dropout2): Dropout(p=0.1, inplace=False)
      )
      (1): TransformerEncoderLayer(
        (self_attn): MultiheadAttention(
          (out_proj): NonDynamicallyQuantizableLinear(in_features=512, out_features=512, bias=True)
        )
        (linear1): Linear(in_features=512, out_features=2048, bias=True)
        (dropout): Dropout(p=0.1, in

In [9]:
x = torch.zeros((4, 32, 10))

In [10]:
t.forward?

Signature:
t.forward(
    src: torch.Tensor,
    tgt: torch.Tensor,
    src_mask: Optional[torch.Tensor] = None,
    tgt_mask: Optional[torch.Tensor] = None,
    memory_mask: Optional[torch.Tensor] = None,
    src_key_padding_mask: Optional[torch.Tensor] = None,
    tgt_key_padding_mask: Optional[torch.Tensor] = None,
    memory_key_padding_mask: Optional[torch.Tensor] = None,
) -> torch.Tensor
Docstring:
Take in and process masked source/target sequences.

Args:
    src: the sequence to the encoder (required).
    tgt: the sequence to the decoder (required).
    src_mask: the additive mask for the src sequence (optional).
    tgt_mask: the additive mask for the tgt sequence (optional).
    memory_mask: the additive mask for the encoder output (optional).
    src_key_padding_mask: the ByteTensor mask for src keys per batch (optional).
    tgt_key_padding_mask: the ByteTensor mask for tgt keys per batch (optional).
    memory_key_padding_mask: the ByteTensor mask for memory keys per bat

In [18]:
t._modules['encoder']

TransformerEncoder(
  (layers): ModuleList(
    (0): TransformerEncoderLayer(
      (self_attn): MultiheadAttention(
        (out_proj): NonDynamicallyQuantizableLinear(in_features=512, out_features=512, bias=True)
      )
      (linear1): Linear(in_features=512, out_features=2048, bias=True)
      (dropout): Dropout(p=0.1, inplace=False)
      (linear2): Linear(in_features=2048, out_features=512, bias=True)
      (norm1): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
      (norm2): LayerNorm((512,), eps=1e-05, elementwise_affine=True)
      (dropout1): Dropout(p=0.1, inplace=False)
      (dropout2): Dropout(p=0.1, inplace=False)
    )
    (1): TransformerEncoderLayer(
      (self_attn): MultiheadAttention(
        (out_proj): NonDynamicallyQuantizableLinear(in_features=512, out_features=512, bias=True)
      )
      (linear1): Linear(in_features=512, out_features=2048, bias=True)
      (dropout): Dropout(p=0.1, inplace=False)
      (linear2): Linear(in_features=2048, out_featu

In [28]:
wishlist = [
    value
    for key, value in torch.nn.modules.__dict__.items()
    if isinstance(value, type) and issubclass(value, torch.nn.Module)
]


In [29]:
wishlist

[torch.nn.modules.module.Module,
 torch.nn.modules.linear.Identity,
 torch.nn.modules.linear.Linear,
 torch.nn.modules.linear.Bilinear,
 torch.nn.modules.linear.LazyLinear,
 torch.nn.modules.conv.Conv1d,
 torch.nn.modules.conv.Conv2d,
 torch.nn.modules.conv.Conv3d,
 torch.nn.modules.conv.ConvTranspose1d,
 torch.nn.modules.conv.ConvTranspose2d,
 torch.nn.modules.conv.ConvTranspose3d,
 torch.nn.modules.conv.LazyConv1d,
 torch.nn.modules.conv.LazyConv2d,
 torch.nn.modules.conv.LazyConv3d,
 torch.nn.modules.conv.LazyConvTranspose1d,
 torch.nn.modules.conv.LazyConvTranspose2d,
 torch.nn.modules.conv.LazyConvTranspose3d,
 torch.nn.modules.activation.Threshold,
 torch.nn.modules.activation.ReLU,
 torch.nn.modules.activation.Hardtanh,
 torch.nn.modules.activation.ReLU6,
 torch.nn.modules.activation.Sigmoid,
 torch.nn.modules.activation.Tanh,
 torch.nn.modules.activation.Softmax,
 torch.nn.modules.activation.Softmax2d,
 torch.nn.modules.activation.LogSoftmax,
 torch.nn.modules.activation.ELU,
 

In [12]:
batch_norm = torch.nn.BatchNorm2d(3)
layer_norm = torch.nn.LayerNorm((3,2))

#instance_norm = torch.nn.InstanceNorm1d(3)

In [16]:
conv = torch.nn.Conv2d(3, 32, 3)

In [19]:
conv.weight

Parameter containing:
tensor([[[[-6.7824e-03,  6.8601e-02, -1.3309e-01],
          [ 7.8424e-02,  2.9884e-02,  7.9124e-02],
          [-6.9095e-02, -1.2547e-03,  3.3231e-02]],

         [[ 1.1468e-01, -5.4619e-02,  9.4577e-02],
          [ 1.1168e-01, -4.9108e-02, -1.1704e-01],
          [ 1.5726e-01,  1.7837e-01, -3.6531e-02]],

         [[-1.0974e-01, -1.7831e-01,  1.9031e-01],
          [ 9.3539e-03, -1.1314e-01, -1.2883e-01],
          [-1.1827e-01,  6.6672e-02,  1.2577e-01]]],


        [[[ 1.6878e-01, -7.9537e-04, -1.1808e-01],
          [ 6.7397e-02,  1.8131e-01,  1.0973e-01],
          [ 1.8140e-01, -8.7085e-02,  6.0301e-03]],

         [[-3.3252e-02, -5.1587e-02, -1.3319e-01],
          [-8.3417e-02,  9.7433e-02,  1.6584e-01],
          [-3.2835e-02,  1.5325e-01,  6.5673e-02]],

         [[ 1.1858e-01,  1.7501e-01,  1.7294e-01],
          [-6.7541e-04, -3.0562e-02, -1.7066e-01],
          [-1.8025e-01, -7.9931e-02, -1.8732e-01]]],


        [[[-1.3819e-01,  1.1653e-01, -1.3730

In [20]:
conv.bias

Parameter containing:
tensor([-0.1171,  0.0065, -0.1017,  0.0967,  0.0845,  0.0323,  0.0955, -0.0843,
         0.0185, -0.0223,  0.0586,  0.0553, -0.0800,  0.0098,  0.0280, -0.0265,
         0.0949, -0.0013,  0.0646, -0.1371,  0.1145,  0.0042, -0.1288,  0.1031,
         0.1849, -0.1484, -0.1718, -0.1155, -0.0631,  0.1688,  0.1342,  0.0402],
       requires_grad=True)

In [26]:
conv._parameters.keys()

odict_keys(['weight', 'bias'])

In [22]:
conv.__dict__.keys()

dict_keys(['training', '_parameters', '_buffers', '_non_persistent_buffers_set', '_backward_hooks', '_is_full_backward_hook', '_forward_hooks', '_forward_pre_hooks', '_state_dict_hooks', '_load_state_dict_pre_hooks', '_load_state_dict_post_hooks', '_modules', 'in_channels', 'out_channels', 'kernel_size', 'stride', 'padding', 'dilation', 'transposed', 'output_padding', 'groups', 'padding_mode', '_reversed_padding_repeated_twice'])

In [18]:
torch.nn.Conv2d?

Init signature:
torch.nn.Conv2d(
    in_channels: int,
    out_channels: int,
    kernel_size: Union[int, Tuple[int, int]],
    stride: Union[int, Tuple[int, int]] = 1,
    padding: Union[str, int, Tuple[int, int]] = 0,
    dilation: Union[int, Tuple[int, int]] = 1,
    groups: int = 1,
    bias: bool = True,
    padding_mode: str = 'zeros',
    device=None,
    dtype=None,
) -> None
Docstring:     
Applies a 2D convolution over an input signal composed of several input
planes.

In the simplest case, the output value of the layer with input size
:math:`(N, C_{\text{in}}, H, W)` and output :math:`(N, C_{\text{out}}, H_{\text{out}}, W_{\text{out}})`
can be precisely described as:

.. math::
    \text{out}(N_i, C_{\text{out}_j}) = \text{bias}(C_{\text{out}_j}) +
    \sum_{k = 0}^{C_{\text{in}} - 1} \text{weight}(C_{\text{out}_j}, k) \star \text{input}(N_i, k)


where :math:`\star` is the valid 2D `cross-correlation`_ operator,
:math:`N` is a batch size, :math:`C` denotes a number of chann

In [6]:
norm.num_features

BatchNorm2d(3, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)

In [47]:
for key, value in torch.nn.__dict__.items():

    if isinstance(value, type) and issubclass(value, torch.nn.Module):
        print(str(value))

<class 'torch.nn.modules.module.Module'>
<class 'torch.nn.modules.linear.Identity'>
<class 'torch.nn.modules.linear.Linear'>
<class 'torch.nn.modules.conv.Conv1d'>
<class 'torch.nn.modules.conv.Conv2d'>
<class 'torch.nn.modules.conv.Conv3d'>
<class 'torch.nn.modules.conv.ConvTranspose1d'>
<class 'torch.nn.modules.conv.ConvTranspose2d'>
<class 'torch.nn.modules.conv.ConvTranspose3d'>
<class 'torch.nn.modules.activation.Threshold'>
<class 'torch.nn.modules.activation.ReLU'>
<class 'torch.nn.modules.activation.Hardtanh'>
<class 'torch.nn.modules.activation.ReLU6'>
<class 'torch.nn.modules.activation.Sigmoid'>
<class 'torch.nn.modules.activation.Tanh'>
<class 'torch.nn.modules.activation.Softmax'>
<class 'torch.nn.modules.activation.Softmax2d'>
<class 'torch.nn.modules.activation.LogSoftmax'>
<class 'torch.nn.modules.activation.ELU'>
<class 'torch.nn.modules.activation.SELU'>
<class 'torch.nn.modules.activation.CELU'>
<class 'torch.nn.modules.activation.GLU'>
<class 'torch.nn.modules.activ

In [23]:
torch.nn.__dir__()

['__name__',
 '__doc__',
 '__package__',
 '__loader__',
 '__spec__',
 '__path__',
 '__file__',
 '__cached__',
 '__builtins__',
 'parameter',
 '_reduction',
 'grad',
 'functional',
 'init',
 'common_types',
 'utils',
 'modules',
 'Module',
 'Identity',
 'Linear',
 'Conv1d',
 'Conv2d',
 'Conv3d',
 'ConvTranspose1d',
 'ConvTranspose2d',
 'ConvTranspose3d',
 'Threshold',
 'ReLU',
 'Hardtanh',
 'ReLU6',
 'Sigmoid',
 'Tanh',
 'Softmax',
 'Softmax2d',
 'LogSoftmax',
 'ELU',
 'SELU',
 'CELU',
 'GLU',
 'GELU',
 'Hardshrink',
 'LeakyReLU',
 'LogSigmoid',
 'Softplus',
 'Softshrink',
 'MultiheadAttention',
 'PReLU',
 'Softsign',
 'Softmin',
 'Tanhshrink',
 'RReLU',
 'L1Loss',
 'NLLLoss',
 'KLDivLoss',
 'MSELoss',
 'BCELoss',
 'BCEWithLogitsLoss',
 'NLLLoss2d',
 'PoissonNLLLoss',
 'CosineEmbeddingLoss',
 'CTCLoss',
 'HingeEmbeddingLoss',
 'MarginRankingLoss',
 'MultiLabelMarginLoss',
 'MultiLabelSoftMarginLoss',
 'MultiMarginLoss',
 'SmoothL1Loss',
 'GaussianNLLLoss',
 'HuberLoss',
 'SoftMarginLoss

In [9]:
x.storage()

 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
[torch.storage._TypedStorage(dtype=torch.float32, device=cpu) of size 60]

In [ ]:
lin.in

In [5]:
model = resnet152()
fe = feature_extraction.create_feature_extractor(model, ['avgpool'])

In [29]:
x = torch.zeros((4, 3, 244, 244), device='meta')

In [31]:
model = model.to('meta')

In [32]:
model(x)

NotImplementedError: convolution_overrideable not implemented. You are likely triggering this with tensor backend other than CPU/CUDA/MKLDNN, if this is intended, please use TORCH_LIBRARY_IMPL to override this function 

In [33]:
lin = torch.nn.Linear(3, 8)

In [40]:
lin._parameters['weight'].shape

torch.Size([8, 3])

In [11]:
out= fe(x)['avgpool']

In [21]:
out.shape

torch.Size([4, 2048, 1, 1])

In [23]:
out.grad_fn = lambda x

In [86]:
x = torch.Tensor([
    [
        [k for k in range(3)] 
        for i in range(3)
    ] for j in range(4)
])

In [87]:
x.shape

torch.Size([4, 3, 3])

In [84]:
lin._parameters['weight'].shape

torch.Size([8, 3])

In [90]:
lin(x).shape

torch.Size([4, 3, 8])

In [105]:
torch.tensor(3, dtype=int)

tensor(3)

In [99]:
torch.ones(1, requires_grad=True) * torch.ones((3, 4, 5))

tensor([[[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1.]]], grad_fn=<MulBackward0>)

In [96]:
torch.Tensor([1], requires_grad=True)

TypeError: new() received an invalid combination of arguments - got (list, requires_grad=bool), but expected one of:
 * (*, torch.device device)
      didn't match because some of the keywords were incorrect: requires_grad
 * (torch.Storage storage)
 * (Tensor other)
 * (tuple of ints size, *, torch.device device)
 * (object data, *, torch.device device)


In [65]:
t1 = (1,2,3,4)
kkt2 = (3,4,5)

In [67]:
(*t1[:-1], t2[-1])

(1, 2, 3, 5)

In [70]:
x.t()

tensor([1.2000, 3.0000, 5.0000])

In [62]:
x.repeat_interleave(4, 0)

tensor([1.2000, 1.2000, 1.2000, 1.2000, 3.0000, 3.0000, 3.0000, 3.0000, 5.0000,
        5.0000, 5.0000, 5.0000])

In [64]:
torch.Tensor.view(x)

TypeError: view() received an invalid combination of arguments - got (), but expected one of:
 * (tuple of ints size)
 * (torch.dtype dtype)


In [28]:
out._requires_grad = True

In [16]:
out.grad_fn(torch.Tensor(0))

RuntimeError: The expanded size of the tensor (8) must match the existing size (0) at non-singleton dimension 3.  Target sizes: [4, 2048, 8, 8].  Tensor sizes: [0]

In [1]:
out.grad_fn

NameError: name 'out' is not defined

In [8]:
model._modules.keys()

odict_keys(['conv1', 'bn1', 'relu', 'maxpool', 'layer1', 'layer2', 'layer3', 'layer4', 'avgpool', 'fc'])

In [4]:
feature_extraction.create_feature_extractor()

Type:        module
String form: <module 'torchvision.models.feature_extraction' from '/home/nathan/.local/lib/python3.9/site-packages/torchvision/models/feature_extraction.py'>
File:        ~/.local/lib/python3.9/site-packages/torchvision/models/feature_extraction.py
Docstring:   <no docstring>


In [5]:
feature_extraction()

Signature:
resnet152(
    *,
    weights: Optional[torchvision.models.resnet.ResNet152_Weights] = None,
    progress: bool = True,
    **kwargs: Any,
) -> torchvision.models.resnet.ResNet
Docstring:
ResNet-152 from `Deep Residual Learning for Image Recognition <https://arxiv.org/pdf/1512.03385.pdf>`__.

.. note::
   The bottleneck of TorchVision places the stride for downsampling to the second 3x3
   convolution while the original paper places it to the first 1x1 convolution.
   This variant improves the accuracy and is known as `ResNet V1.5
   <https://ngc.nvidia.com/catalog/model-scripts/nvidia:resnet_50_v1_5_for_pytorch>`_.

Args:
    weights (:class:`~torchvision.models.ResNet152_Weights`, optional): The
        pretrained weights to use. See
        :class:`~torchvision.models.ResNet152_Weights` below for
        more details, and possible values. By default, no pre-trained
        weights are used.
    progress (bool, optional): If True, displays a progress bar of the
        dow